# Generated by Django 4.2.3 on 2023-07-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_create_time_post_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_time',
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
